[package]
name = "sf"
version = "0.1.0"
authors = ["Apollo Hogan <apollo.hogan@gmail.com>"]
edition = "2018"

[dependencies]
libc = "*"
libm = "*"
num-complex = "*"
num-integer = "*"
num-rational = "*"
num-traits = "*"
num = "*"
once_cell = "*"
paste = "*"

# approximate equality asserts
#approx = "*"

#microbenchmarking crate:
#criterion = "*"

#for eigenvalue calcs:
#nalgebra = "*"

#heavy overhead, but interesting:
#plotlib = "*"
#plotters = "*"

#maybe:
#num-bigint = "*"
#num-iter = "*"

#not on cargo.rs:
#qd = "*"
