[package]
name = "sf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.sf_impl]
path = "../sf_impl"

[dependencies.sf_hex_float]
path = "../sf_hex_float"