binop_separator = "Front"
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
comment_width = 120
control_brace_style = "AlwaysSameLine"
#disable_all_formatting = true
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Compressed"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
max_width = 120
space_after_colon = true
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = false
