/* license details */

#ifndef include_sfc_h
#define include_sfc_h

#pragma once

/* This file is autogenerated by cbindgen.  Manual editing is contraindicated. */

#define MUST_USE_FUNC __attribute__((warn_unused_result))

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

MUST_USE_FUNC double sf_airy_ai(double x);

MUST_USE_FUNC double sf_airy_bi(double x);

MUST_USE_FUNC double sf_erf(double x);

MUST_USE_FUNC double sf_erfc(double x);

MUST_USE_FUNC double sf_erf_inv(double x);

MUST_USE_FUNC double sf_exp(double x);

MUST_USE_FUNC double sf_exp_m1(double x);

MUST_USE_FUNC double sf_exp_m1vx(double x);

MUST_USE_FUNC double sf_expn(intptr_t n, double x);

MUST_USE_FUNC double sf_exp_men(intptr_t n, double x);

MUST_USE_FUNC double sf_exp_menx(intptr_t n, double x);

MUST_USE_FUNC double sf_gamma(double x);

MUST_USE_FUNC double sf_lngamma(double x);

MUST_USE_FUNC double sf_digamma(double x);

MUST_USE_FUNC double sf_beta(double a, double b);

MUST_USE_FUNC double sf_zeta(double x);

MUST_USE_FUNC double sf_zeta_m1(double x);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* include_sfc_h */
