/* license details */

#ifndef include_sfc_h
#define include_sfc_h

#pragma once

/* This file is autogenerated by cbindgen.  Manual editing is contraindicated. */

#define MUST_USE_FUNC __attribute__((warn_unused_result))

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

MUST_USE_FUNC double sf_exp(double x);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* include_sfc_h */
